# Generated by Django 5.2.7 on 2025-10-14 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="food_images/"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("north", "North Indian"), ("south", "South Indian")],
                        default="north",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="booking",
            name="delivery_partner",
        ),
        migrations.AlterField(
            model_name="booking",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="booking",
            name="food_items",
            field=models.ManyToManyField(to="bookings.food"),
        ),
    ]
